volumes:
  mysql-store:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app
    ports:
    - "8081:8080"

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./src/:/app
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    restart: always
    user: 1000:1000
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
      MYSQL_DISABLE_UPGRADE_BACKUP: "1"
    volumes:
      - ./mysql-data:/var/lib/mysql-data
